language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coveralls readme_renderer
script:
- coverage run --source pyethapp setup.py test
- python setup.py check --restructuredtext --strict
after_success:
- coveralls
notifications:
  slack:
    secure: MLpiCgdrAqs0GCTdf9zC84/ly93xxQSTcmY2guAHCMGp+DjaRk/fWIrBMPJVE/ZI7FYV6BcDX4pv5l2QUrmubdFpygayTz3V+/ELtabtFIO7MR9zExFhLUMaRP5+YDNJZJ9rA4TI8r00o4VQUM+tS12cR1NbzTIXMm2OMLC+2Uw=
deploy:
  provider: pypi
  user: ethereum_pypi_automated
  password:
    secure: NxQNT56QVXkgmDvnPFdtnVr0N0VRpkSTd5DBh1iiasf4pVessln0Uu8QxeQipeUpCKpB7+mCb4Bu2VFNQ7fN60M/wWENSQdl2gBz+GfOjt6TBPffUy1m6pNhtC3WCkqwOkLRe3KE0Dyy0wKqK3/QvyLwNZCoIUMk2CijvhS1UA0=
  on:
    tags: true
    repo: ethereum/pyethapp
    branch: develop
  distributions: sdist bdist_wheel
